default_settings: null

behaviors:
  ListeningAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 102400
      learning_rate: 0.00025
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play: null
    behavioral_cloning: null

env_settings:
  env_path: AudioRL.exe
  env_args: null
  base_port: 5005
  num_envs: 4
  seed: -1

engine_settings:
  width: 84
  height: 84
  quality_level: 0 #should help limit botteneck
  time_scale: 150 #faster training
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true #should run faster

environment_parameters: null

checkpoint_settings:
  run_id: AudioRL_Run1
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: true
  inference: false
  results_dir: results

torch_settings:
  device: cuda      

debug: false
